// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UserInterfaceABS.UserInterface
{
    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Linq;
    using System.Xml.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    
    #line 1 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class MVCModelGenerator_v1_0 : MVCModelGenerator_v1_0Base
    {
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            this.Write("\r\n");
            
            #line 18 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
   
	// Set abstraction specific type and single file specific extension
	//TransformGenerator< UserInterfaceAbstractionType >(GenerateRoot, ".designer.html");	
	GenerateRoot();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 23 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
 
	public Tuple<string, string>[] GetGeneratorContent(params string[] xmlFileNames)
	{
		List<Tuple<string, string>> result = new List<Tuple<string, string>>();
		foreach(string xmlFileName in xmlFileNames)
		{
			UserInterfaceAbstractionType abs = LoadXml<UserInterfaceAbstractionType>(xmlFileName);
			CurrentAbstraction = abs;
			foreach(var userInterface in CurrentAbstraction.UserInterfaces ?? new UserInterfaceType[0])
			{
				// Models\NewContractModel.Generated.cs 
				CurrentUserInterface = userInterface;
				string controllerFileName = userInterface.name + "Models.Generated.cs";
				string content = TransformText();
				this.GenerationEnvironment.Clear();
				string xmlInputDirectory = Path.GetDirectoryName(xmlFileName);
				string outputFile = Path.Combine(xmlInputDirectory, "Models", controllerFileName);
				outputFile = outputFile.Replace(@"\In\", @"\Out\");
				outputFile = outputFile.Replace(@"\ADM\Abstractions\AbstractionContent\UserInterface\Out\", @"\CubioSite\");
				result.Add(Tuple.Create(outputFile, content));
			}
		}
		return result.ToArray();
	}
	void SetCurrentAbstraction(object abs)
	{
		CurrentAbstraction = ( UserInterfaceAbstractionType ) abs;
	}
	
	UserInterfaceAbstractionType CurrentAbstraction;
	UserInterfaceType CurrentUserInterface;
	ControllerActionType CurrentControllerAction;
	
	void GenerateRoot()
	{
		GenerateUserInterface(CurrentUserInterface);
	}
	
	void GenerateUserInterface(UserInterfaceType uiType)
	{
		foreach(var controllerAction in uiType.ControllerActions)
		{
			CurrentControllerAction = controllerAction;
			GenerateController(controllerAction);
		}
	}
	
	void GenerateController(ControllerActionType controllerAction)
	{

        
        #line default
        #line hidden
        
        #line 72 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
this.Write("\t\t/*\r\n\t\t ControllerAction for ");

        
        #line default
        #line hidden
        
        #line 74 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(controllerAction.name));

        
        #line default
        #line hidden
        
        #line 74 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
this.Write(" doing ");

        
        #line default
        #line hidden
        
        #line 74 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(controllerAction.designDesc));

        
        #line default
        #line hidden
        
        #line 74 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"
this.Write("\r\n\t\t */\r\n");

        
        #line default
        #line hidden
        
        #line 76 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\MVCModelGenerator_v1_0.tt"

	}
	
	

        
        #line default
        #line hidden
        
        #line 2 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	enum AbstractionShareLevel
	{
		Local,
		Shared,
		Modular,
	}
	
	bool IsLocal
	{
		get {
			return ShareLevel == AbstractionOptions.GeneralTypeShareLevel.Local;
		}
	}
	
	AbstractionOptions.AbstractionOptionsType CurrentOptions;
	AbstractionOptions.GeneralTypeShareLevel ShareLevel {
		get {
			return CurrentOptions.General.shareLevel;
		}
	}
	
	void TransformGenerator<AbstractionType>(Action rootLevelGenerator, string sharedSingleFileExtension)
	{
		// Abstraction(s) that are supposed to be shared must be shared by default.
		// This is simply because any change to "shared" makes it modified compared to the shared version.
		// Thus making abstraction "local" allows also making the changes that make it behave like "local".
		// To make the abstraction "local" make following changes:
		// 1. Modify the output - directive right on top of the file (2nd line) from "?" to ".designer.cs"
		// 2. Set the AbstractionShareLevel below to Shared 
		// 3. After the changes, the abstraction starts to generate its output right below the template:
		// - Change the .cs file properties so that it doesn't compile in the abstraction-project
		// - Link the output .cs file to appropriate projects (to replace the links from AbstractionContent/Out directory)
		// 4. If necessary, copy over and alter the include-files specified for common includes
		
		// ShareLevel = AbstractionShareLevel.Shared;
		
		string templateDirectoryPath = Path.GetDirectoryName(Host.TemplateFile);
		DirectoryInfo dirInfo = new DirectoryInfo(templateDirectoryPath);
		dirInfo = dirInfo.Parent;
		string optionsFile = Path.Combine(dirInfo.FullName, "Options.xml");
		CurrentOptions = LoadXml<AbstractionOptions.AbstractionOptionsType>(optionsFile);

		if(ShareLevel != AbstractionOptions.GeneralTypeShareLevel.Modular)
		{
			string directoryName = GetContentDirectoryFromTemplateFullPath(Host.TemplateFile, IsLocal == false);
			string[] xmlFileNames = Directory.GetFiles(directoryName, "*.xml");
			
			foreach(string xmlFileName in xmlFileNames)
			{
				AbstractionType current = LoadXml<AbstractionType>(xmlFileName);
				SetCurrentAbstraction(current);
				rootLevelGenerator();
			}
		} 
		else
		{
			rootLevelGenerator();
		}
		
		if(ShareLevel == AbstractionOptions.GeneralTypeShareLevel.Shared)
		{
			WriteContentToSingleOutput(Host.TemplateFile, sharedSingleFileExtension);
		}
	}
	
	
	string GetContentDirectoryFromTemplateFullPath(string templateFullPath, bool isShared)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir =  isShared ? @"In\Content_v1_0" : "Content_v1_0";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		if(isShared) {
			System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
			absRootDirInfo = absRootDirInfo.Parent;
			string abstractionName = absRootDirInfo.Name;
			directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		}
		return directoryName;
	}
	
	void WriteContentToSingleOutput(string templateFullPath, string extension)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir = "Out";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		string contentFileName = System.IO.Path.GetFileNameWithoutExtension(templateFullPath) + extension;
		System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
		absRootDirInfo = absRootDirInfo.Parent;
		string abstractionName = absRootDirInfo.Name;
		directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		string contentFullName = Path.Combine(directoryName, contentFileName);
		string contentData = this.GenerationEnvironment.ToString();
		this.GenerationEnvironment.Clear();
		File.WriteAllText(contentFullName, contentData);
	}

	T LoadXml<T>(string xmlFileName) {
		using(FileStream fStream = File.OpenRead(xmlFileName)) {
			XmlSerializer serializer = new XmlSerializer(typeof(T));
			T result = (T) serializer.Deserialize(fStream);
			fStream.Close();
			return result;
		}
	}

	void BeginNamespace(string namespaceName) {
		
        
        #line default
        #line hidden
        
        #line 109 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 109 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 109 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" { \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 110 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	}

	void EndBlock() {
		
        
        #line default
        #line hidden
        
        #line 114 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" } ");

        
        #line default
        #line hidden
        
        #line 114 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"

	}

		
	static string RemoveScands(string sourceString) {
		return sourceString.Replace('ä', 'a').Replace('Ä', 'A').Replace('å', 'a').Replace('Å', 'A').Replace('ö', 'o').Replace('Ö', 'O');
	}
	
	public class GenerationItem
	{
		public string FileName;
		public string Content;
	}
	

        
        #line default
        #line hidden
        
        #line 1 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\..\..\abscommon\CommonInclude\Common\AbstractionOptions_namespace.ttinclude"

public class AbstractionOptions { 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AbstractionOptions.xsd")]
[System.Xml.Serialization.XmlRootAttribute("AbstractionOptions", Namespace="http://tempuri.org/AbstractionOptions.xsd", IsNullable=false)]
public partial class AbstractionOptionsType {
    
    private GeneralType generalField;
    
    /// <remarks/>
    public GeneralType General {
        get {
            return this.generalField;
        }
        set {
            this.generalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AbstractionOptions.xsd")]
public partial class GeneralType {
    
    private GeneralTypeShareLevel shareLevelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GeneralTypeShareLevel shareLevel {
        get {
            return this.shareLevelField;
        }
        set {
            this.shareLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/AbstractionOptions.xsd")]
public enum GeneralTypeShareLevel {
    
    /// <remarks/>
    Local,
    
    /// <remarks/>
    Shared,
    
    /// <remarks/>
    Modular,
}
} 
        
        #line default
        #line hidden
        
        #line 1 "C:\work\abs\Caloom\Abstractions\UserInterfaceABS\UserInterface\UserInterface_v1_0.ttinclude"

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("UserInterfaceAbstraction", Namespace="", IsNullable=false)]
public partial class UserInterfaceAbstractionType {
    
    private UserInterfaceType[] userInterfacesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UserInterface", IsNullable=false)]
    public UserInterfaceType[] UserInterfaces {
        get {
            return this.userInterfacesField;
        }
        set {
            this.userInterfacesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UserInterfaceType {
    
    private PagesType pagesField;
    
    private UIProcessModelType uIProcessModelField;
    
    private ViewType[] viewsField;
    
    private ControllerActionType[] controllerActionsField;
    
    private ClassType[] semanticModelField;
    
    private RootType[] dataContextField;
    
    private string nameField;
    
    private string domainNameField;
    
    /// <remarks/>
    public PagesType Pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    public UIProcessModelType UIProcessModel {
        get {
            return this.uIProcessModelField;
        }
        set {
            this.uIProcessModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("View", IsNullable=false)]
    public ViewType[] Views {
        get {
            return this.viewsField;
        }
        set {
            this.viewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ControllerAction", IsNullable=false)]
    public ControllerActionType[] ControllerActions {
        get {
            return this.controllerActionsField;
        }
        set {
            this.controllerActionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UIClass", IsNullable=false)]
    public ClassType[] SemanticModel {
        get {
            return this.semanticModelField;
        }
        set {
            this.semanticModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Root", IsNullable=false)]
    public RootType[] DataContext {
        get {
            return this.dataContextField;
        }
        set {
            this.dataContextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domainName {
        get {
            return this.domainNameField;
        }
        set {
            this.domainNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PagesType {
    
    private PagesTypePage pageField;
    
    /// <remarks/>
    public PagesTypePage Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesTypePage {
    
    private object itemField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Layout", typeof(LayoutType))]
    [System.Xml.Serialization.XmlElementAttribute("Sections", typeof(PagesTypePageSections))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LayoutType {
    
    private object itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlowLayout", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("GridLayout", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("StackLayout", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("TableLayout", typeof(object))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ViewType {
    
    private ViewLayoutType viewLayoutField;
    
    private object[] itemsField;
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    public ViewLayoutType ViewLayout {
        get {
            return this.viewLayoutField;
        }
        set {
            this.viewLayoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChildView", typeof(ChildViewType))]
    [System.Xml.Serialization.XmlElementAttribute("ViewProperty", typeof(ViewPropertyType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ViewLayoutType {
    
    private GridLayoutType itemField;
    
    private ViewLayoutTypeLayoutType layoutTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GridLayout")]
    public GridLayoutType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ViewLayoutTypeLayoutType layoutType {
        get {
            return this.layoutTypeField;
        }
        set {
            this.layoutTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GridLayoutType {
    
    private ColumnType[] columnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column")]
    public ColumnType[] Column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ColumnType {
    
    private string nameField;
    
    private string designDescField;
    
    private string labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ViewLayoutTypeLayoutType {
    
    /// <remarks/>
    FlowLayout,
    
    /// <remarks/>
    VerticalStack,
    
    /// <remarks/>
    HorizontalStack,
    
    /// <remarks/>
    Grid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChildViewType {
    
    private string childViewNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string childViewName {
        get {
            return this.childViewNameField;
        }
        set {
            this.childViewNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ViewPropertyType {
    
    private object itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    private string labelTextField;
    
    private object infoField;
    
    private string nameField;
    
    private string dataTypeField;
    
    private bool isRequiredField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AttachmentBlob", typeof(AttachmentBlobType))]
    [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("ChoiceList", typeof(ChoiceListType))]
    [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(DateTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("Lookup", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("MultipleChoiceList", typeof(MultipleChoiceListType))]
    [System.Xml.Serialization.XmlElementAttribute("Numeric", typeof(NumericType))]
    [System.Xml.Serialization.XmlElementAttribute("String", typeof(StringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string LabelText {
        get {
            return this.labelTextField;
        }
        set {
            this.labelTextField = value;
        }
    }
    
    /// <remarks/>
    public object Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AttachmentBlobType : VisibleControlType {
    
    private AttachmentBlobTypeMediaType mediaTypeField;
    
    private string extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AttachmentBlobTypeMediaType mediaType {
        get {
            return this.mediaTypeField;
        }
        set {
            this.mediaTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AttachmentBlobTypeMediaType {
    
    /// <remarks/>
    AnyBinary,
    
    /// <remarks/>
    Image,
    
    /// <remarks/>
    Audio,
    
    /// <remarks/>
    Video,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiChoiceListType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceListType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ButtonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentBlobType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VisibleControlType : ControlType {
    
    private LabelType[] labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Label")]
    public LabelType[] Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LabelType {
    
    private string languageField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomViewType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DisplayType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VisibleControlType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiChoiceListType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceListType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ButtonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentBlobType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InfoType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContainerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommandAreaType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WhenType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VisibleContainerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldSetType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public abstract partial class ControlType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CustomViewType : ControlType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DisplayType : ControlType {
    
    private string fromControlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fromControl {
        get {
            return this.fromControlField;
        }
        set {
            this.fromControlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InfoType : ControlType {
    
    private string contentField;
    
    private string languageField;
    
    /// <remarks/>
    public string Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommandAreaType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WhenType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VisibleContainerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldSetType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ContainerType : ControlType {
    
    private object[] contentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AttachmentBlob", typeof(AttachmentBlobType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Boolean", typeof(BooleanType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ChoiseList", typeof(ChoiceListType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(DescriptionType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Display", typeof(DisplayType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", typeof(FieldSetType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Hidden", typeof(HiddenType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Info", typeof(InfoType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MultiChoiseList", typeof(MultiChoiceListType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Numeric", typeof(NumericType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Page", typeof(PageType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", typeof(ParameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Text", typeof(TextType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("When", typeof(WhenType), IsNullable=false)]
    public object[] Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BooleanType : VisibleControlType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChoiceListType : VisibleControlType {
    
    private ChoiceType[] choiceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Choice")]
    public ChoiceType[] Choice {
        get {
            return this.choiceField;
        }
        set {
            this.choiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChoiceType {
    
    private ChoiceTypeLabel[] labelField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Label")]
    public ChoiceTypeLabel[] Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ChoiceTypeLabel {
    
    private string languageField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DescriptionType : VisibleControlType {
    
    private int minLengthField;
    
    private int maxLengthField;
    
    private bool isRequiredField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minLength {
        get {
            return this.minLengthField;
        }
        set {
            this.minLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FieldSetType : VisibleContainerType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldSetType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VisibleContainerType : ContainerType {
    
    private LabelType[] labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Label")]
    public LabelType[] Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PageType : VisibleContainerType {
    
    private PageTypePageLocation pageLocationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PageTypePageLocation pageLocation {
        get {
            return this.pageLocationField;
        }
        set {
            this.pageLocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum PageTypePageLocation {
    
    /// <remarks/>
    First,
    
    /// <remarks/>
    Last,
    
    /// <remarks/>
    Middle,
    
    /// <remarks/>
    Disconnected,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HiddenType {
    
    private string nameField;
    
    private string dataTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MultiChoiceListType : VisibleControlType {
    
    private ChoiceType[] choiceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Choice")]
    public ChoiceType[] Choice {
        get {
            return this.choiceField;
        }
        set {
            this.choiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NumericType : VisibleControlType {
    
    private int rangeMinField;
    
    private int rangeMaxField;
    
    private int scaleField;
    
    private int unitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int rangeMin {
        get {
            return this.rangeMinField;
        }
        set {
            this.rangeMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int rangeMax {
        get {
            return this.rangeMaxField;
        }
        set {
            this.rangeMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ParameterType {
    
    private string nameField;
    
    private string dataTypeField;
    
    private bool isRequiredField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TextType : VisibleControlType {
    
    private int minLengthField;
    
    private int maxLengthField;
    
    private bool isRequiredField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minLength {
        get {
            return this.minLengthField;
        }
        set {
            this.minLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WhenType : ContainerType {
    
    private string conditionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CommandAreaType : ContainerType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ButtonType : VisibleControlType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DateTimeType {
    
    private DateTimeTypeDateTimeType dateTimeTypeField;
    
    private DateTimeTypeUtcDisplayStyle utcDisplayStyleField;
    
    public DateTimeType() {
        this.utcDisplayStyleField = DateTimeTypeUtcDisplayStyle.Local;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DateTimeTypeDateTimeType dateTimeType {
        get {
            return this.dateTimeTypeField;
        }
        set {
            this.dateTimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DateTimeTypeUtcDisplayStyle.Local)]
    public DateTimeTypeUtcDisplayStyle utcDisplayStyle {
        get {
            return this.utcDisplayStyleField;
        }
        set {
            this.utcDisplayStyleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DateTimeTypeDateTimeType {
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    Time,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DateTimeTypeUtcDisplayStyle {
    
    /// <remarks/>
    Local,
    
    /// <remarks/>
    UTC,
    
    /// <remarks/>
    LocalWithTimezoneInfo,
    
    /// <remarks/>
    UTCWithTimezoneInfo,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MultipleChoiceListType {
    
    private MultipleChoiceListTypeControlType controlTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MultipleChoiceListTypeControlType controlType {
        get {
            return this.controlTypeField;
        }
        set {
            this.controlTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum MultipleChoiceListTypeControlType {
    
    /// <remarks/>
    CheckBox,
    
    /// <remarks/>
    Dropdown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StringType {
    
    private int minLengthField;
    
    private int maxLengthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minLength {
        get {
            return this.minLengthField;
        }
        set {
            this.minLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    AttachmentBlob,
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    ChoiceList,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    Lookup,
    
    /// <remarks/>
    MultipleChoiceList,
    
    /// <remarks/>
    Numeric,
    
    /// <remarks/>
    String,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UIProcessModelType {
    
    private LaunchPadType[] launchPadsField;
    
    private UIProcessType[] uIProcessesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LaunchPad", IsNullable=false)]
    public LaunchPadType[] LaunchPads {
        get {
            return this.launchPadsField;
        }
        set {
            this.launchPadsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UIProcess", IsNullable=false)]
    public UIProcessType[] UIProcesses {
        get {
            return this.uIProcessesField;
        }
        set {
            this.uIProcessesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LaunchPadType {
    
    private InputMappingType[] inputMappingField;
    
    private ProcessExitActionType[] processExitActionField;
    
    private string nameField;
    
    private string designDescField;
    
    private string uiProcessNameToLaunchField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InputMapping")]
    public InputMappingType[] InputMapping {
        get {
            return this.inputMappingField;
        }
        set {
            this.inputMappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProcessExitAction")]
    public ProcessExitActionType[] ProcessExitAction {
        get {
            return this.processExitActionField;
        }
        set {
            this.processExitActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uiProcessNameToLaunch {
        get {
            return this.uiProcessNameToLaunchField;
        }
        set {
            this.uiProcessNameToLaunchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InputMappingType {
    
    private string processInputFullPropertyNameField;
    
    private string uiFieldNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string processInputFullPropertyName {
        get {
            return this.processInputFullPropertyNameField;
        }
        set {
            this.processInputFullPropertyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uiFieldName {
        get {
            return this.uiFieldNameField;
        }
        set {
            this.uiFieldNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProcessExitActionType {
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UIProcessType {
    
    private ProcessInputType processInputField;
    
    private BeforeExecuteValidationType[] beforeExecuteValidationField;
    
    private object[] processFlowField;
    
    private ProcessOutputType processOutputField;
    
    private string nameField;
    
    private string designDescField;
    
    private string semanticModelClassNameField;
    
    /// <remarks/>
    public ProcessInputType ProcessInput {
        get {
            return this.processInputField;
        }
        set {
            this.processInputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BeforeExecuteValidation")]
    public BeforeExecuteValidationType[] BeforeExecuteValidation {
        get {
            return this.beforeExecuteValidationField;
        }
        set {
            this.beforeExecuteValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
    public object[] ProcessFlow {
        get {
            return this.processFlowField;
        }
        set {
            this.processFlowField = value;
        }
    }
    
    /// <remarks/>
    public ProcessOutputType ProcessOutput {
        get {
            return this.processOutputField;
        }
        set {
            this.processOutputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semanticModelClassName {
        get {
            return this.semanticModelClassNameField;
        }
        set {
            this.semanticModelClassNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProcessInputType {
    
    private string semanticModelClassNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semanticModelClassName {
        get {
            return this.semanticModelClassNameField;
        }
        set {
            this.semanticModelClassNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BeforeExecuteValidationType {
    
    private string nameField;
    
    private string designDescField;
    
    private string conditionExpressionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string conditionExpression {
        get {
            return this.conditionExpressionField;
        }
        set {
            this.conditionExpressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExecutionItemType {
    
    private string nameField;
    
    private string designDescField;
    
    private ExecutionItemTypeStepType stepTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ExecutionItemTypeStepType stepType {
        get {
            return this.stepTypeField;
        }
        set {
            this.stepTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ExecutionItemTypeStepType {
    
    /// <remarks/>
    User,
    
    /// <remarks/>
    SystemUI,
    
    /// <remarks/>
    SystemBusinessLogic,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ForEachType {
    
    private object[] executionBlockField;
    
    private string nameField;
    
    private string designDescField;
    
    private string inputCollectionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
    public object[] ExecutionBlock {
        get {
            return this.executionBlockField;
        }
        set {
            this.executionBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string inputCollection {
        get {
            return this.inputCollectionField;
        }
        set {
            this.inputCollectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IfType {
    
    private object[] executionBlockField;
    
    private ElseIfType[] elseIfField;
    
    private ElseType elseField;
    
    private string nameField;
    
    private string designDescField;
    
    private string conditionExpressionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
    public object[] ExecutionBlock {
        get {
            return this.executionBlockField;
        }
        set {
            this.executionBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElseIf")]
    public ElseIfType[] ElseIf {
        get {
            return this.elseIfField;
        }
        set {
            this.elseIfField = value;
        }
    }
    
    /// <remarks/>
    public ElseType Else {
        get {
            return this.elseField;
        }
        set {
            this.elseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string conditionExpression {
        get {
            return this.conditionExpressionField;
        }
        set {
            this.conditionExpressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ElseIfType {
    
    private object[] executionBlockField;
    
    private string nameField;
    
    private string designDescField;
    
    private string conditionExpressionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
    public object[] ExecutionBlock {
        get {
            return this.executionBlockField;
        }
        set {
            this.executionBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string conditionExpression {
        get {
            return this.conditionExpressionField;
        }
        set {
            this.conditionExpressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ElseType {
    
    private object[] executionBlockField;
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
    public object[] ExecutionBlock {
        get {
            return this.executionBlockField;
        }
        set {
            this.executionBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProcessOutputType {
    
    private string semanticModelClassNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semanticModelClassName {
        get {
            return this.semanticModelClassNameField;
        }
        set {
            this.semanticModelClassNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RootType {
    
    private string nameField;
    
    private string classNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string className {
        get {
            return this.classNameField;
        }
        set {
            this.classNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ControllerActionType {
    
    private object[] viewStructureField;
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AttachmentBlob", typeof(AttachmentBlobType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Boolean", typeof(BooleanType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ChoiseList", typeof(ChoiceListType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(DescriptionType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Display", typeof(DisplayType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", typeof(FieldSetType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Hidden", typeof(HiddenType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Info", typeof(InfoType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MultiChoiseList", typeof(MultiChoiceListType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Numeric", typeof(NumericType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Page", typeof(PageType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", typeof(ParameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Text", typeof(TextType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("When", typeof(WhenType), IsNullable=false)]
    public object[] ViewStructure {
        get {
            return this.viewStructureField;
        }
        set {
            this.viewStructureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PropertyType {
    
    private object itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string labelTextField;
    
    private object infoField;
    
    private string nameField;
    
    private string dataTypeField;
    
    private bool isRequiredField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AttachmentBlob", typeof(AttachmentBlobType))]
    [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("ChoiceList", typeof(ChoiceListType))]
    [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(DateTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("Lookup", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("MultipleChoiceList", typeof(MultipleChoiceListType))]
    [System.Xml.Serialization.XmlElementAttribute("Numeric", typeof(NumericType))]
    [System.Xml.Serialization.XmlElementAttribute("String", typeof(StringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string LabelText {
        get {
            return this.labelTextField;
        }
        set {
            this.labelTextField = value;
        }
    }
    
    /// <remarks/>
    public object Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isRequired {
        get {
            return this.isRequiredField;
        }
        set {
            this.isRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    AttachmentBlob,
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    ChoiceList,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    Lookup,
    
    /// <remarks/>
    MultipleChoiceList,
    
    /// <remarks/>
    Numeric,
    
    /// <remarks/>
    String,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ClassType {
    
    private PropertyType[] propertiesField;
    
    private string nameField;
    
    private string designDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
    public PropertyType[] Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ClassesType {
    
    private string namespaceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string namespaceName {
        get {
            return this.namespaceNameField;
        }
        set {
            this.namespaceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    FlowLayout,
    
    /// <remarks/>
    GridLayout,
    
    /// <remarks/>
    StackLayout,
    
    /// <remarks/>
    TableLayout,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesTypePageSections {
    
    private PagesTypePageSectionsSection sectionField;
    
    /// <remarks/>
    public PagesTypePageSectionsSection Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesTypePageSectionsSection {
    
    private LayoutType layoutField;
    
    private string nameField;
    
    /// <remarks/>
    public LayoutType Layout {
        get {
            return this.layoutField;
        }
        set {
            this.layoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class MVCModelGenerator_v1_0Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
