//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace UserInterface_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UserInterfaceAbstraction", Namespace="", IsNullable=false)]
    public partial class UserInterfaceAbstractionType {
        
        private UserInterfaceType[] userInterfacesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UserInterface", IsNullable=false)]
        public UserInterfaceType[] UserInterfaces {
            get {
                return this.userInterfacesField;
            }
            set {
                this.userInterfacesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInterfaceType {
        
        private PagesType pagesField;
        
        private UIProcessModelType uIProcessModelField;
        
        private ViewType[] viewsField;
        
        private ClassType[] semanticModelField;
        
        private RootType[] dataContextField;
        
        private string nameField;
        
        private string domainNameField;
        
        /// <remarks/>
        public PagesType Pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        public UIProcessModelType UIProcessModel {
            get {
                return this.uIProcessModelField;
            }
            set {
                this.uIProcessModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("View", IsNullable=false)]
        public ViewType[] Views {
            get {
                return this.viewsField;
            }
            set {
                this.viewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UIClass", IsNullable=false)]
        public ClassType[] SemanticModel {
            get {
                return this.semanticModelField;
            }
            set {
                this.semanticModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Root", IsNullable=false)]
        public RootType[] DataContext {
            get {
                return this.dataContextField;
            }
            set {
                this.dataContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string domainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagesType {
        
        private PagesTypePage pageField;
        
        /// <remarks/>
        public PagesTypePage Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PagesTypePage {
        
        private object itemField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Layout", typeof(LayoutType))]
        [System.Xml.Serialization.XmlElementAttribute("Sections", typeof(PagesTypePageSections))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayoutType {
        
        private object itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FlowLayout", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("GridLayout", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("StackLayout", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TableLayout", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewType {
        
        private ViewLayoutType viewLayoutField;
        
        private object[] itemsField;
        
        private string nameField;
        
        private string designDescField;
        
        /// <remarks/>
        public ViewLayoutType ViewLayout {
            get {
                return this.viewLayoutField;
            }
            set {
                this.viewLayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildView", typeof(ChildViewType))]
        [System.Xml.Serialization.XmlElementAttribute("ViewProperty", typeof(ViewPropertyType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewLayoutType {
        
        private GridLayoutType itemField;
        
        private ViewLayoutTypeLayoutType layoutTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GridLayout")]
        public GridLayoutType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ViewLayoutTypeLayoutType layoutType {
            get {
                return this.layoutTypeField;
            }
            set {
                this.layoutTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GridLayoutType {
        
        private ColumnType[] columnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column")]
        public ColumnType[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColumnType {
        
        private string nameField;
        
        private string designDescField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ViewLayoutTypeLayoutType {
        
        /// <remarks/>
        FlowLayout,
        
        /// <remarks/>
        VerticalStack,
        
        /// <remarks/>
        HorizontalStack,
        
        /// <remarks/>
        Grid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChildViewType {
        
        private string childViewNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string childViewName {
            get {
                return this.childViewNameField;
            }
            set {
                this.childViewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewPropertyType {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string labelTextField;
        
        private object infoField;
        
        private string nameField;
        
        private string dataTypeField;
        
        private bool isRequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentBlob", typeof(AttachmentBlobType))]
        [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ChoiceList", typeof(ChoiceListType))]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(DateTimeType))]
        [System.Xml.Serialization.XmlElementAttribute("Lookup", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MultipleChoiceList", typeof(MultipleChoiceListType))]
        [System.Xml.Serialization.XmlElementAttribute("Numeric", typeof(NumericType))]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(StringType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string LabelText {
            get {
                return this.labelTextField;
            }
            set {
                this.labelTextField = value;
            }
        }
        
        /// <remarks/>
        public object Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AttachmentBlobType {
        
        private AttachmentBlobTypeMediaType mediaTypeField;
        
        private string extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttachmentBlobTypeMediaType mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum AttachmentBlobTypeMediaType {
        
        /// <remarks/>
        AnyBinary,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Audio,
        
        /// <remarks/>
        Video,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChoiceListType {
        
        private ChoiceListTypeControlType controlTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChoiceListTypeControlType controlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ChoiceListTypeControlType {
        
        /// <remarks/>
        CheckBox,
        
        /// <remarks/>
        Dropdown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DateTimeType {
        
        private DateTimeTypeDateTimeType dateTimeTypeField;
        
        private DateTimeTypeUtcDisplayStyle utcDisplayStyleField;
        
        public DateTimeType() {
            this.utcDisplayStyleField = DateTimeTypeUtcDisplayStyle.Local;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateTimeTypeDateTimeType dateTimeType {
            get {
                return this.dateTimeTypeField;
            }
            set {
                this.dateTimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DateTimeTypeUtcDisplayStyle.Local)]
        public DateTimeTypeUtcDisplayStyle utcDisplayStyle {
            get {
                return this.utcDisplayStyleField;
            }
            set {
                this.utcDisplayStyleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum DateTimeTypeDateTimeType {
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Time,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum DateTimeTypeUtcDisplayStyle {
        
        /// <remarks/>
        Local,
        
        /// <remarks/>
        UTC,
        
        /// <remarks/>
        LocalWithTimezoneInfo,
        
        /// <remarks/>
        UTCWithTimezoneInfo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultipleChoiceListType {
        
        private MultipleChoiceListTypeControlType controlTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MultipleChoiceListTypeControlType controlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum MultipleChoiceListTypeControlType {
        
        /// <remarks/>
        CheckBox,
        
        /// <remarks/>
        Dropdown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumericType {
        
        private int rangeMinField;
        
        private int rangeMaxField;
        
        private int scaleField;
        
        private int unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rangeMin {
            get {
                return this.rangeMinField;
            }
            set {
                this.rangeMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rangeMax {
            get {
                return this.rangeMaxField;
            }
            set {
                this.rangeMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StringType {
        
        private int minLengthField;
        
        private int maxLengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minLength {
            get {
                return this.minLengthField;
            }
            set {
                this.minLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        AttachmentBlob,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        ChoiceList,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Lookup,
        
        /// <remarks/>
        MultipleChoiceList,
        
        /// <remarks/>
        Numeric,
        
        /// <remarks/>
        String,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessOutputType {
        
        private string semanticModelClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string semanticModelClassName {
            get {
                return this.semanticModelClassNameField;
            }
            set {
                this.semanticModelClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeforeExecuteValidationType {
        
        private string nameField;
        
        private string designDescField;
        
        private string conditionExpressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionExpression {
            get {
                return this.conditionExpressionField;
            }
            set {
                this.conditionExpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInputType {
        
        private string semanticModelClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string semanticModelClassName {
            get {
                return this.semanticModelClassNameField;
            }
            set {
                this.semanticModelClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UIProcessType {
        
        private ProcessInputType processInputField;
        
        private BeforeExecuteValidationType[] beforeExecuteValidationField;
        
        private object[] processFlowField;
        
        private ProcessOutputType processOutputField;
        
        private string nameField;
        
        private string designDescField;
        
        private string semanticModelClassNameField;
        
        /// <remarks/>
        public ProcessInputType ProcessInput {
            get {
                return this.processInputField;
            }
            set {
                this.processInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BeforeExecuteValidation")]
        public BeforeExecuteValidationType[] BeforeExecuteValidation {
            get {
                return this.beforeExecuteValidationField;
            }
            set {
                this.beforeExecuteValidationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
        public object[] ProcessFlow {
            get {
                return this.processFlowField;
            }
            set {
                this.processFlowField = value;
            }
        }
        
        /// <remarks/>
        public ProcessOutputType ProcessOutput {
            get {
                return this.processOutputField;
            }
            set {
                this.processOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string semanticModelClassName {
            get {
                return this.semanticModelClassNameField;
            }
            set {
                this.semanticModelClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecutionItemType {
        
        private string nameField;
        
        private string designDescField;
        
        private ExecutionItemTypeStepType stepTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExecutionItemTypeStepType stepType {
            get {
                return this.stepTypeField;
            }
            set {
                this.stepTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ExecutionItemTypeStepType {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        SystemUI,
        
        /// <remarks/>
        SystemBusinessLogic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForEachType {
        
        private object[] executionBlockField;
        
        private string nameField;
        
        private string designDescField;
        
        private string inputCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
        public object[] ExecutionBlock {
            get {
                return this.executionBlockField;
            }
            set {
                this.executionBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string inputCollection {
            get {
                return this.inputCollectionField;
            }
            set {
                this.inputCollectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IfType {
        
        private object[] executionBlockField;
        
        private ElseIfType[] elseIfField;
        
        private ElseType elseField;
        
        private string nameField;
        
        private string designDescField;
        
        private string conditionExpressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
        public object[] ExecutionBlock {
            get {
                return this.executionBlockField;
            }
            set {
                this.executionBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElseIf")]
        public ElseIfType[] ElseIf {
            get {
                return this.elseIfField;
            }
            set {
                this.elseIfField = value;
            }
        }
        
        /// <remarks/>
        public ElseType Else {
            get {
                return this.elseField;
            }
            set {
                this.elseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionExpression {
            get {
                return this.conditionExpressionField;
            }
            set {
                this.conditionExpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElseIfType {
        
        private object[] executionBlockField;
        
        private string nameField;
        
        private string designDescField;
        
        private string conditionExpressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
        public object[] ExecutionBlock {
            get {
                return this.executionBlockField;
            }
            set {
                this.executionBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionExpression {
            get {
                return this.conditionExpressionField;
            }
            set {
                this.conditionExpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElseType {
        
        private object[] executionBlockField;
        
        private string nameField;
        
        private string designDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExecutionItem", typeof(ExecutionItemType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ForEach", typeof(ForEachType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("If", typeof(IfType), IsNullable=false)]
        public object[] ExecutionBlock {
            get {
                return this.executionBlockField;
            }
            set {
                this.executionBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessExitActionType {
        
        private string nameField;
        
        private string designDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputMappingType {
        
        private string processInputFullPropertyNameField;
        
        private string uiFieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string processInputFullPropertyName {
            get {
                return this.processInputFullPropertyNameField;
            }
            set {
                this.processInputFullPropertyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uiFieldName {
            get {
                return this.uiFieldNameField;
            }
            set {
                this.uiFieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LaunchPadType {
        
        private InputMappingType[] inputMappingField;
        
        private ProcessExitActionType[] processExitActionField;
        
        private string nameField;
        
        private string designDescField;
        
        private string uiProcessNameToLaunchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InputMapping")]
        public InputMappingType[] InputMapping {
            get {
                return this.inputMappingField;
            }
            set {
                this.inputMappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessExitAction")]
        public ProcessExitActionType[] ProcessExitAction {
            get {
                return this.processExitActionField;
            }
            set {
                this.processExitActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uiProcessNameToLaunch {
            get {
                return this.uiProcessNameToLaunchField;
            }
            set {
                this.uiProcessNameToLaunchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UIProcessModelType {
        
        private LaunchPadType[] launchPadsField;
        
        private UIProcessType[] uIProcessesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LaunchPad", IsNullable=false)]
        public LaunchPadType[] LaunchPads {
            get {
                return this.launchPadsField;
            }
            set {
                this.launchPadsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UIProcess", IsNullable=false)]
        public UIProcessType[] UIProcesses {
            get {
                return this.uIProcessesField;
            }
            set {
                this.uIProcessesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RootType {
        
        private string nameField;
        
        private string classNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassesType {
        
        private string namespaceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string namespaceName {
            get {
                return this.namespaceNameField;
            }
            set {
                this.namespaceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassType {
        
        private PropertyType[] propertiesField;
        
        private string nameField;
        
        private string designDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public PropertyType[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyType {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string labelTextField;
        
        private object infoField;
        
        private string nameField;
        
        private string dataTypeField;
        
        private bool isRequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentBlob", typeof(AttachmentBlobType))]
        [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ChoiceList", typeof(ChoiceListType))]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(DateTimeType))]
        [System.Xml.Serialization.XmlElementAttribute("Lookup", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MultipleChoiceList", typeof(MultipleChoiceListType))]
        [System.Xml.Serialization.XmlElementAttribute("Numeric", typeof(NumericType))]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(StringType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string LabelText {
            get {
                return this.labelTextField;
            }
            set {
                this.labelTextField = value;
            }
        }
        
        /// <remarks/>
        public object Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AttachmentBlob,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        ChoiceList,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Lookup,
        
        /// <remarks/>
        MultipleChoiceList,
        
        /// <remarks/>
        Numeric,
        
        /// <remarks/>
        String,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        FlowLayout,
        
        /// <remarks/>
        GridLayout,
        
        /// <remarks/>
        StackLayout,
        
        /// <remarks/>
        TableLayout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PagesTypePageSections {
        
        private PagesTypePageSectionsSection sectionField;
        
        /// <remarks/>
        public PagesTypePageSectionsSection Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PagesTypePageSectionsSection {
        
        private LayoutType layoutField;
        
        private string nameField;
        
        /// <remarks/>
        public LayoutType Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
